Задание:

Реализовать предсказание настроений с помощью классических алгоритмов + tf-idf на основе данных твиттов и наивным байесом.

На "отлично" - попробовать обучить любой из пройденных алгоритмов на основе эмбеддингов взвешенных по attention или с помощью классических от TruncatedSVD на основе полиномиальных от tf-idf с (1-3) биграммами.

Поскольку глубокие сети еще впереди код конвертации списка предложений в эмбеддинг по ссылке выше.

Так как мы чаще всего работаем с нампай массивами в обучении, используйте:

sentence_embeddings.detach().numpy()

## Загрузка

In [1]:
# import kagglehub
# path = kagglehub.dataset_download("arkhoshghalb/twitter-sentiment-analysis-hatred-speech", output_dir='../data/dataset_text')

In [3]:
import numpy as np
import pandas as pd

import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline

import warnings
warnings.simplefilter('ignore')

In [5]:
df_rawtext = pd.read_csv('data/dataset_text/train.csv')

In [6]:
df_rawtext.head()

   id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation

In [7]:
df_text = df_rawtext.drop('id', axis=1)
df_test_text = df_text.copy()
df_text.groupby('label').count()

       tweet
label
0      29720
1       2242

## План

1. Разбить на трейн/тест

2. Предобработка: нижний регистр, очистка от пунктуации, лемматизация

3. Составить функцию аугментации

4. Векторизация и UMAP обзор

5. Наивный Байес  и логрег

6. TF-IDF с n-граммами -> TrancatedSVD -> smote на svd-векторы -> логрег

7. Bert?

8. Анализ всех алгоритмов на тесте по метрикам F1, precision, recall

## 1 Разбиение

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df_text.drop('label', axis=1), df_text['label'])

print([t.shape for t in [X_train, X_test, y_train, y_test]])

[(23971, 1), (7991, 1), (23971,), (7991,)]

## 2 Предобработка

Напишем предворительную функцию которая:
1. Переводит в нижний регистр
2. Очистка от пунктуации
3. Проводит лемматизацию

Для предобработки текста и словаря синонимов - библиотеку NTLK

In [13]:
import string
import re
import spacy
import en_core_web_sm

In [ ]:
def preprocessor(raw_text, to_lowercase=True, punctuation=True, lemmatization=True):
    '''
    Функция принимает сырой текст: приводит к нижнему регистру, 
    убирает пунктуация, токенизурует, приводит слова токены к лемме.
    '''
    if to_lowercase:
        text = raw_text.lower()
    else: 
        text = raw_text
        
    if punctuation:    
        pattern = f'[{re.escape(string.punctuation)}]'
        text = re.sub(pattern, ' ', text)

    tokens = word_tokenize(text)

    if lemmatization:
        clean_tokens = []
        
        for word in tokens:
            if word not in stop_words:
                clean_tokens.append(lemmatizer.lemmatize(word))

        return ' '.join(clean_tokens)
        
    return tokens

## Семплинг

### Оверсемплинг

EDA - создаем дополнительные примеры недостающего класса 4 методами: замена синонимами, вставка синонима, перестановка пары слов, удаление слов.

Для этого буду использовать библиотеку textaugment. Для предобработки текста (стемминг и лемматизация) и словаря синонимов - библиотеку NTLK

In [ ]:
import nltk
import string
import re

from textaugment import EDA
from nltk.corpus import stopwords 
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

In [ ]:
nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('punkt_tab')

In [ ]:
from textaugment import Wordnet

In [ ]:
stop_words = stopwords.words('english')
lemmatizer = WordNetLemmatizer()
def preprocessor(raw_text):
    text = raw_text.lower()

    pattern = f'[{re.escape(string.punctuation)}]'
    text = re.sub(pattern, ' ', text)

    tokens = word_tokenize(text)

    clean_tokens = []

    for word in tokens:
        if word not in stop_words:
            clean_tokens.append(lemmatizer.lemmatize(word))

    return ' '.join(clean_tokens)

In [ ]:
df_clean_text = pd.concat([df_text['label'], df_text['tweet'].apply(preprocessor)], axis=1)
df_clean_text.head()

In [ ]:
def augment_text(df_text, alpha=0.1, n=3, method='sr'):
    '''
    method sr - synonym replacement
        rd - random deletion
        rw - random swap 
        rs - random insertion
    '''
    eda = EDA(random_state=322)
    
    mode_of_action= {'sr': eda.synonym_replacement,
        'rd': eda.random_deletion, 
        'rw': eda.random_swap,
        'rs': eda.random_insertion}
    
    new_df_text = pd.DataFrame(columns=df_text.columns)

    for text in df_text:
        for i in range(n):
            aug_series = pd.Series(index=text['label'], data=mode_of_action[method](text['tweet']))
            new_df_text = pd.concat([new_df_text, aug_series])
    return new_df_text

In [ ]:
df_minor = df_clean_text[df_clean_text['label']==1]
df_minor.shape

In [ ]:
df_aug_minor = augment_text(df_minor)